spring:
  datasource:
    url: jdbc:mysql://localhost:3305/demo
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}


