spring:
  datasource:
    hikari:
      batch:
        jdbc-url: jdbc:mysql://localhost:3305/batch
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
      demo:
        jdbc-url: jdbc:mysql://localhost:3305/demo?rewriteBatchedStatements=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1234
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}
#      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
logging:
  level:
    root: info
